apiVersion: v2
name: app-template
description: Reusable Helm chart for JavaScript applications with optional PostgreSQL
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - javascript
  - nodejs
  - nextjs
  - react
  - postgresql
maintainers:
  - name: CloudWarrior
    email: contact@cloudwarrior.io
dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
