{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-template.fullname" . }}-secrets
  namespace: {{ include "app-template.namespace" . }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | default (randAlphaNum 32) | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-template.fullname" . }}-postgresql
  namespace: {{ include "app-template.namespace" . }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | default (randAlphaNum 32) | quote }}
  password: {{ .Values.postgresql.auth.password | default (randAlphaNum 32) | quote }}
{{- end }}
